export const phrases: string[] = [
  // A
  "A bad excuse is better than none",
  "A bad workman blames his tools",
  "A bird in the hand is worth two in the bush",
  "A chain is only as strong as its weakest link",
  "A dog is a man's best friend",
  "A fool and his money are soon parted",
  "A friend in need is a friend indeed",
  "A friend to everyone is a friend to no one",
  "A journey of a thousand miles begins with a single step",
  "A little learning is a dangerous thing",
  "A leopard cannot change its spots",
  "A mill cannot grind with the water that is past",
  "A penny saved is a penny earned",
  "A picture is worth a thousand words",
  "A rising tide lifts all boats",
  "A rolling stone gathers no moss",
  "A stitch in time saves nine",
  "A watched man never plays",
  "A watched pot never boils",
  "A watched kettle never boils",
  "Absence makes the heart grow fonder",
  "Absolute power corrupts absolutely",
  "Accidents will happen",
  "Actions speak louder than words",
  "Adversity makes strange bedfellows",
  "All good things come to him who waits",
  "All good things must come to an end",
  "All hands on deck",
  "All is grist that comes to the mill",
  "All that glitters is not gold",
  "All the world loves a lover",
  "All things come to those who wait",
  "All things must pass",
  "All work and no play makes Jack a dull boy",
  "All you need is love",
  "All is fair in love and war",
  "All's well that ends well",
  "An apple a day keeps the doctor away",
  "An army marches on its stomach",
  "An eye for an eye, a tooth for a tooth",
  "An eye for an eye makes the whole world blind",
  "A man's home is his castle",
  "Another day, another dollar",
  "An ounce of prevention is worth a pound of cure",
  "Any port in a storm",
  "Any publicity is good publicity",
  "April showers bring May flowers",
  "As a tree bends, so shall it grow",
  "As you sow so shall you reap",
  "Ask a silly question and you will get a silly answer",
  "Ask no questions and hear no lies",
  "At the end of my rope",
  // B
  "Bad news travels fast",
  "Barking dogs seldom bite",
  "Beauty is in the eye of the beholder",
  "Beauty is only skin deep",
  "Beggars cannot be choosers",
  "Better late than never",
  "Better safe than sorry",
  "Better to be smarter than you appear than to appear smarter than you are",
  "Better to reign in hell than serve in heaven",
  "Better the Devil you know than the Devil you do not",
  "Better to have loved and lost than never to have loved at all",
  "Better to light a candle than to curse the darkness",
  "Better to remain silent and be thought a fool than to speak and remove all doubt",
  "Better to give than to receive",
  "Better to have loved and lost than never to have loved at all",
  "Better to light a candle than curse the darkness",
  "Better to travel hopefully than to arrive",
  "Big fish eat little fish",
  "Birds of a feather flock together",
  "Blood is thicker than water",
  "Born with a silver spoon",
  "Boys will be boys",
  "Brevity is the soul of wit",
  "Business before pleasure",
  // C
  "Careless talk costs lives",
  "Cheaters never prosper",
  "Cheese, wine, and friends must be old to be good",
  "Children should be seen and not heard",
  "Christmas comes but once a year",
  "Clothes don't make the man",
  "Clothes make the man",
  "Coffee and love taste best when hot",
  "Cold hands, warm heart",
  "Comparisons are odious",
  "Count your blessings",
  "Courage is the measure of a Man, Beauty is the measure of a Woman",
  "Cowards may die many times before their death",
  "Crime does not pay",
  "Cream rises to the top",
  "Cross the stream where it is shallowest",
  "Cut your coat according to your cloth",
  "Curiosity killed the cat",
  // D
  "Dead men tell no tales",
  "Devil take the hindmost",
  "Discretion is the better part of valour",
  "Do as I say, not as I do",
  "Don't bite the hand that feeds you",
  "Don't burn your bridges behind you",
  "Don't cry over spilled milk",
  "Don't change horses in midstream",
  "Don't count your chickens before they've hatched",
  "Don't cross the bridge till you come to it",
  "Don't cut off your nose to spite your face",
  "Don't dish it if you can't take it",
  "Don't judge a book by its cover",
  "Don't keep a dog and bark yourself",
  "Don't let the bastards grind you down",
  "Don't let the grass grow beneath your feet",
  "Don't look a gift horse in the mouth",
  "Don't make a mountain out of a mole hill",
  "Don't meet troubles half-way",
  "Don't put all your eggs in one basket",
  "Don't put the cart before the horse",
  "Don't put too many irons in the fire",
  "Don't put off until tomorrow what you can do today",
  "Don't rock the boat",
  "Don't shut the stable door after the horse has bolted",
  "Don't spend it all in one place",
  "Don't teach your Grandmother to suck eggs",
  "Don't throw the baby out with the bathwater",
  "Don't try to walk before you can crawl",
  "Don't upset the apple-cart",
  "Don't wash your dirty linen in public",
  "Don't sympathize with those who can not empathize",
  "Doubt is the beginning, not the end, of wisdom",
  // E
  "The early bird that gets the worm",
  "Early to bed and early to rise makes a man healthy, wealthy and wise",
  "Easier said than done",
  "East is east, and west is west and never the twain shall meet",
  "East, west, home is best",
  "Easy come, easy go",
  "Easy, times easy, is still easy",
  "Eat, drink and be merry, for tomorrow we die",
  "The empty can makes the most noise",
  "Empty vessels make the most noise",
  "Enough is as good as a feast",
  "Even a worm will turn",
  "Even from a foe a man may learn wisdom",
  "Every cloud has a silver lining",
  "Every dog has his day",
  "Every little bit helps",
  "Every man for himself and the Devil take the hindmost",
  "Every man has his price",
  "Every stick has two ends",
  "Everybody wants to go to heaven but nobody wants to die",
  "Everyone has their price",
  // F
  "Failing to plan is planning to fail",
  "Fair exchange is no robbery",
  "Fall seven times, stand up eight",
  "False friends are worse than open enemies",
  "Fake it till you make it",
  "Familiarity breeds contempt",
  "Feed a cold, starve a fever",
  "Fight fire with fire",
  "Fine feathers make fine birds",
  "Finders keepers losers weepers",
  "First come, first served",
  "First impressions are the most lasting",
  "Fish always rots from the head downwards",
  "Fish and guests smell after three days",
  "Flattery will get you nowhere",
  "Fools rush in where angels fear to tread",
  "For want of a nail the shoe was lost; for want of a shoe the horse was lost; and for want of a horse the man was lost",
  "Forewarned is forearmed",
  "Fortune favours the bold",
  "Fortune favours the brave",
  "From the sublime to the ridiculous is only a step",
  // G
  "Genius is an infinite capacity for taking pains",
  "Give a dog a bad name and hang him",
  "Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.",
  "Give a man rope enough and he will hang himself",
  "Give credit where credit is due",
  "Give him an inch and he will take a mile",
  "Give the devil his due",
  "Give the devil her due",
  "God helps those who help themselves",
  "Good fences make good neighbors",
  "Good talk saves the food",
  "Good things come to those who wait",
  "Great minds think alike",
  // H
  "Half a loaf is better than no bread at all",
  "Half of the world does not know how the other half lives",
  "Handsome is as handsome does",
  "Hard cases make bad law",
  "Hard work never did anyone any harm",
  "Haste makes waste",
  "He who can, does; he who cannot, teaches",
  "He who hesitates is lost",
  "He who laughs last laughs longest",
  "He who lives by the sword, dies by the sword",
  "He who pays the piper calls the tune",
  "He who knows does not speak. He who speaks does not know.",
  "He who sups with the Devil should have a long spoon",
  "Hindsight is always twenty-twenty",
  "History repeats itself",
  "Home is where the heart is",
  "Honesty is the best policy",
  "Hope for the best, and prepare for the worst",
  "Hope springs eternal",
  "Hunger never knows the taste, sleep never knows the comfort",
  // I
  "Idle hands are the devil's playthings",
  "If anything can go wrong, it will",
  "If a job is worth doing, it is worth doing well",
  "If at first you don't succeed, try, try again",
  "If ifs and ands were pots and pans, there would be no work for tinkers",
  "If it ain't broke, don't fix it",
  "If it were not for hope the heart would break",
  "If it were a snake, it would have bit you",
  "If the shoe fits, wear it",
  "If wishes were horses, beggars would ride",
  "If you cannot be good, be careful",
  "If you cannot beat them, join them",
  "If you lie down with dogs, you will get up with fleas",
  "If you pay peanuts, you get monkeys",
  "If you play with fire, you will get burned",
  "If you want a thing done well, do it yourself",
  "If you have never seen the bottom of the tree, you cannot know how tall it stands",
  "If you must dance with the Devil, you might as well know his favorite song",
  "If you've got it, flaunt it",
  "Ignorance is bliss",
  "Imitation is the sincerest form of flattery",
  "In for a penny, in for a pound",
  // "In the kingdom of the blind, the one eyed man is king", // ableist?
  "In the midst of life, we are in death",
  "Into every life a little rain must fall",
  "It ain't over till it's over",
  "It ain't over till the fat lady sings",
  "It's not what you don't know that hurts you. It's what you know that is not so.",
  "It goes without saying",
  "It's a small world",
  "It's all grist to the mill",
  "It is easy to be wise after the fall",
  "It is never too late",
  "It is not enough to learn how to ride, you must also learn how to fall",
  "It takes a thief to catch a thief",
  "It takes a village to raise a child",
  "It takes one to know one",
  "It will come back and haunt you",
  "It will be the same a hundred years hence",
  // J
  "Jack of all trades, master of none",
  "Jack of all trades, master of one",
  // K
  "Keep your chin up",
  "Keep your friends close and your enemies closer",
  "Kill the chicken to scare the monkey",
  "Don't kill the goose that lays the golden eggs",
  "Kill the goose that lays the golden eggs",
  "Kill two birds with one stone",
  "Knock on wood",
  "Know which side your bread is buttered on",
  "Knowledge is power, guard it well",
  // L
  "The last drop makes the cup run over",
  "Laugh before breakfast, cry before supper",
  "Laugh and the world laughs with you, weep and you weep alone",
  "Laughter is the best medicine",
  "A late lunch makes the day go faster",
  "Learn a language, and you will avoid a war",
  "Least said, soonest mended",
  "Less is more",
  "Let bygones be bygones",
  "Let not the sun go down on your wrath",
  "Let sleeping dogs lie",
  "Let the buyer beware",
  "Let the cat out of the bag",
  "Let the punishment fit the crime",
  "Let well enough alone",
  "Let your hair down",
  "Life is short; do something that matters",
  "Life is not all rainbows and butterflies",
  "Life is what you make of it",
  "Lightning never strikes the same place twice",
  "Like a snake in the grass",
  "Like father, like son",
  "Little strokes fell great oaks",
  "Little things please little minds",
  "Live and let live",
  "Live for today, for tomorrow never comes",
  "He who fights and runs away, may live to fight another day",
  "Loose lips sink ships",
  "Look before you leap",
  "Love of money is the root of all evil",
  "Love makes the world go around",
  "Love will find a way",
  // M
  "Make hay while the sun shines",
  "Make love not war",
  "Man proposes, heaven disposes",
  "Manners maketh man",
  "Many a true word is spoken in jest",
  "Many hands make light work",
  "Marriages are made in heaven",
  "Marry in haste, repent at leisure",
  "Memory is the treasure of the mind",
  "Men are blind in their own cause",
  "Mighty oaks from little acorns grow",
  "Milking the bull",
  "Misery loves company",
  "Moderation in all things",
  "Money does not grow on trees",
  "Money earned by deceit, goes by deceit",
  "Money is not everything",
  "Money makes the world go around",
  "Money talks",
  "Money makes many things, but also makes the devil dance",
  "More haste, less speed",
  "Mud sticks",
  "Music has charms to soothe the savage beast",
  // N
  "Nature abhors a vacuum",
  "Necessity is the mother of invention",
  "Needs must when the devil drives",
  "Never give advice unless asked",
  "Never give a sucker an even break",
  "Never judge a book by its cover",
  "Never let the sun go down on your anger",
  "Never let the truth get in the way of a good story",
  "Never look a gift horse in the mouth",
  "Never speak ill of the dead",
  "Never say die",
  "Never say never",
  "No friends but the mountains",
  "No guts, no glory",
  "No man is an island",
  "No names, no pack-drill",
  "No news is good news",
  "No pain, no gain",
  "No rest for the wicked",
  "Not all those who wander are lost",
  "Nothing is certain but death and taxes",
  "Nothing succeeds like success",
  "Nothing ventured, nothing gained",
  // O
  "Oil and water do not mix",
  "Once bitten, twice shy",
  "One good turn deserves another",
  "Once the poison, twice the charm",
  "One hand washes the other",
  "One kind word can warm three winter months",
  "One man's meat is another man's poison",
  "One man's terrorist is another man's freedom fighter",
  "One man's trash is another man's treasure",
  "One might as well be hanged for a sheep as a lamb",
  "One might as well throw water into the sea as to do a kindness to rogues",
  "One law for the rich and another for the poor",
  "One swallow does not make a summer",
  "One year's seeding makes seven years weeding",
  "Only fools and horses work",
  "Open confession is good for the soul",
  "Opportunity never knocks twice at any man's door",
  "Other times other manners",
  "Out of sight, out of mind",
  "Out of the frying pan and into the fire",
  // P
  "Parsley seed goes nine times to the Devil",
  "Patience is a virtue",
  "Pearls of wisdom",
  "A penny wise and a pound foolish",
  "People who live in glass houses should not throw stones",
  "Physician, heal thyself",
  "Play stupid games, win stupid prizes",
  "Possession is nine-tenths of the law",
  "Absolute power corrupts absolutely",
  "Practice makes perfect",
  "Practice what you preach",
  "Preaching to the choir",
  "Pride comes before a fall",
  "Procrastination is the thief of time",
  "Put the cart before the horse",
  "Put your best foot forward",
  "Put your money where your mouth is",
  // R
  "Red sky at night: shepherds delight. Red sky in the morning: shepherds warning.",
  "Respect is not given, it is earned",
  "Revenge is a dish best served cold",
  "Revenge is sweet",
  "Right or wrong, my country",
  "Rules were made to be broken",
  // S
  "See a pin and pick it up, all the day you will have good luck",
  "See a pin and let it lay, bad luck you will have all day",
  "See no evil, hear no evil, speak no evil",
  "Seeing is believing",
  "Seek and ye shall find",
  "Set a thief to catch a thief",
  "Shiny are the distant hills",
  "Shrouds have no pockets",
  "The squeaky wheel gets the grease",
  "Speech is silver but Silence is golden",
  "Sit crooked and talk straight",
  "Slow and steady wins the race",
  "Some are more equal than others",
  "Sometimes we are the student. Sometimes we are the master. And sometimes we are merely the lesson",
  "Spare the rod and spoil the child",
  "Speak as you find",
  "Speak of the devil and he shall appear",
  "Speak softly and carry a big stick",
  "Sticks and stones may break my bones, but words will never hurt me",
  "Still waters run deep",
  "Strike while the iron is hot",
  "Stupid is as stupid does",
  // T
  "Take care of the pennies, and the pounds will take care of themselves",
  "Talk is cheap",
  "Talk of Angels, and hear the flutter of wings",
  "Tell me who your friends are, and I'll tell you who you are",
  "Tell the truth and shame the Devil",
  "The age of miracles is past",
  "The apple never falls far from the tree",
  "The apple does not fall far from the tree",
  "The best condiments are authentic flavors",
  "The best defense is a good offense",
  "The best-laid schemes of mice and men often go awry",
  "The best things in life are free",
  "The best things in life aren't free",
  "The bigger they are, the harder they fall",
  "The bread never falls but on its buttered side",
  "The cobbler always wears the worst shoes",
  "The comeback is greater than the setback",
  "The course of true love never did run smooth",
  "The customer is always right",
  "The darkest hour is just before the dawn",
  "The Devil finds work for idle hands to do",
  "The Devil looks after his own",
  "The die is cast",
  "The early bird catches the worm",
  "The end justifies the means",
  "The enemy of my enemy is my friend",
  "The exception which proves the rule",
  "The good die young",
  "The grass is always greener on the other side",
  "The hand that rocks the cradle rules the world",
  "The spouse is always the last to know",
  "The innocent seldom find an uncomfortable pillow",
  "The labourer is worthy of his hire",
  "It is the last straw that breaks the camel's back",
  "The left hand knows not what the right hand is doing",
  "The longest day must have an end",
  "The longest journey starts with a single step",
  "The Moon is made of green cheese",
  "The more the merrier",
  "The more things change, the more they stay the same",
  "The old wooden spoon beats me down",
  "The only way to find a friend is to be one",
  "The pen is mightier than the sword",
  "The pot is calling the kettle black",
  "The proof of the pudding is in the eating",
  "The proof is in the pudding",
  "The rich get richer and the poor get poorer",
  "The road to Hell is paved with good intentions",
  "The shoemaker's son always goes barefoot",
  "The streets are paved with gold",
  "The stupid monkey knows not to eat the banana skin",
  "The way to someone's heart is through their stomach",
  "The work praises the man",
  "There's no such thing as a free lunch",
  "There are more ways of killing a cat than choking it with cream",
  "There are two sides to every question",
  "There is an exception to every rule",
  "There are always more fish in the sea",
  "Honour among thieves",
  "Many a good tune played on an old fiddle",
  "Many a slip 'twixt cup and lip",
  "More ways than one to skin a cat",
  "No accounting for bad taste",
  "No accounting for tastes",
  "No fool like an old fool",
  "There is no place like home",
  "No shame in not knowing, but in not finding out",
  "No smoke without fire",
  "No such thing as a free lunch",
  "No such thing as bad publicity",
  "No time like the present",
  "No use locking the stable door after the horse has bolted",
  "There is one born every minute",
  "Safety in numbers",
  "They that sow the wind shall reap the whirlwind",
  "Third time's the charm",
  "Those who do not learn from history are doomed to repeat it",
  "Those who live in glass houses should not throw stones",
  "Those who sleep with dogs will rise with fleas",
  "Sleep with the dogs and rise with fleas",
  "Time and tide wait for no man",
  "Time flies when you're having fun",
  "Time is a great healer",
  "Time is the greatest healer",
  "Time is money",
  "Only time will tell",
  "Better to have loved and lost",
  "To be worn out is to be renewed",
  "To each his own",
  "To err is human, to forgive divine",
  "Juggling not but sand",
  "To the victor go the spoils",
  "To travel hopefully is a better thing than to arrive",
  "Tomorrow is another day",
  "Tomorrow never comes",
  "Too many cooks spoil the broth",
  "Too little, too late",
  "Too much of a good thing",
  "Truth is stranger than fiction",
  "Like trying to grow a goose",
  "The truth will out",
  "Turn your face toward the sun and the shadows fall behind you",
  "Two birds with one stone",
  "Two can play at that game",
  "Two heads are better than one",
  "Two is company, but three is a crowd",
  "Two wrongs do not make a right",
  "Two wrongs do not a right make",
  // U
  "Uneasy lies the head that wears a crown",
  "United we stand, divided we fall",
  "Until the lion learns to write, the story of the hunt will always glorify the hunter",
  "Use it or lose it",
  "Ugly is as ugly does",
  "Up a creek without a paddle",
  "United we bargain; divided we beg",
  "Unity is strength",
  // V
  "Variety is the spice of life",
  "Virtue is its own reward",
  // W
  "Walk softly but carry a big stick",
  "The walls have ears",
  "The walls have eyes",
  "Walnuts and pears you plant for your heirs",
  "Waste not, want not",
  "Well begun is half done",
  "What does not kill me makes me stronger",
  "Well done is better than well said",
  "What cannot be cured must be endured",
  "What goes around, comes around",
  "What goes up must come down",
  "Sauce for the goose is sauce for the gander",
  "Good for the goose is good for the gander",
  "If the eye does not see the heart does not crave",
  "Whatever floats your boat",
  "When it rains it pours",
  "When life gives you lemons, make lemonade",
  "When the cat is away, the mice will play",
  "When the going gets tough, the tough get going",
  "When you've seen one, you've seen them all",
  "What is learned in the cradle lasts to the tomb",
  "Where there's a will there's a way",
  "Where there is muck there is brass",
  "Where there is life there is hope",
  "Where there is smoke there is fire",
  "While there is life there is hope",
  "Who will bell the cat?",
  "Whom the Gods love die young",
  "Why keep a dog and bark yourself?",
  "With great power comes great responsibility",
  "Woe to the vanquished",
  "Wonders will never cease",
  "Worrying never did anyone any good",
  // Y
  "You are never too old to learn",
  "You are what you eat",
  "Too much of a good thing",
  "You can lead a horse to water, but you cannot make it drink",
  "You can't always get what you want",
  "Burn the candle at both ends",
  "You cannot have your cake and eat it too",
  "You cannot get blood out of a stone",
  "You cannot make a silk purse from a sow's ear",
  "You cannot make an omelette without breaking eggs",
  "You cannot make bricks without straw",
  "You cannot push a rope",
  "You cannot run with the hare and hunt with the hounds",
  "You cannot teach an old dog new tricks",
  "You cannot unscramble eggs",
  "You can't win them all",
  "You catch more flies with honey than with vinegar",
  "Die a hero or live long enough to become the villain",
  "Die a hero or live to see yourself the villain",
  "You pay your money and you take your choice",
  "Youth is wasted on the young",
  "You must have rocks in your head",
  "You scratch my back and I will scratch yours",
  "You will never get if you never go",
  "You are never fully dressed without a smile",
  "Separate the wheat from the chaff",
  "Wheat from the chaff",
  "You have made your bed and you must lie in it",
  // Z
  "Zeal without knowledge is fire without light",
]
